spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vaultkeep}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:kakarot23}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:balajigbalaji4321@gmail.com}
spring.mail.password=${MAIL_PASSWORD:qwry ehcn htyz kzmq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=${PORT:8080}

app.jwt.secret=${JWT_SECRET:4a6f8b2c1d9e0f3a5b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a}
app.jwt.expiration-ms=3600000

app.encryption.secret=${ENCRYPTION_SECRET:kM2vR9qLzXpN4tYw7hCbFj6sDgAe3oV1uZ5xI8mQpKrW0nBcLy}